### PR TITLE
Update Gulp to version 4

### PR DESCRIPTION
**Pull request by mrkmiller**
- Update to Gulp 4
- Remove the gulp-help package
- Remove Sassdoc
- Remove SingularityGS

### CODE REVIEW

**Comment by mrkmiller** [comment]
You can test this by installing the branch via npm `npm install --save-dev ucdavis/ucd-theme-tasks#gulp4`

**Comment by ahorn-ucd** [comment]
`npx gulp` fails.

**Comment by ahorn-ucd** [comment]
`anthonyhorn@C02Y42X4JGH6 site (master) $ npx gulp
[15:38:46] Using gulpfile ~/localhost/ncst/docroot/sites/default/themes/site/gulpfile.js
[15:38:46] Starting 'default'...
[15:38:46] Starting 'compile'...
[15:38:46] Starting 'watch'...
[15:38:46] Starting 'js'...
[15:38:46] Starting 'watch:js'...
[15:38:46] Starting 'watch:css'...
[15:38:46] Finished 'watch:js' after 26 ms
[15:38:46] Finished 'watch:css' after 29 ms
[15:38:46] Finished 'watch' after 29 ms
(node:55359) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
[15:38:48] Version: webpack 4.32.2
Built at: 05/29/2019 3:38:48 PM
         Asset      Size  Chunks             Chunk Names
    scripts.js  1.67 KiB       0  [emitted]  main
scripts.js.map  6.76 KiB       0  [emitted]  main
Entrypoint main = scripts.js scripts.js.map
[15:38:48] Finished 'js' after 2.34 s
[15:38:48] Starting 'sass'...
Error in plugin "sass"
Message:
    sass/style.scss
Error: File to import not found or unreadable: singularitygs.
        on line 4 of sass/style.scss
>> @import "singularitygs";

   ^

[15:38:48] gulp-notify: [CSS Error - Line 4] sass/style.scss
Error: File to import not found or unreadable: singularitygs.
        on line 4 of sass/style.scss
>> @import "singularitygs";

   ^

[15:38:48] 'sass' errored after 86 ms
[15:38:48] TypeError: this.emit is not a function
    at DestroyableTransform.errorHandler (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/ucd-theme-tasks/gulp_tasks/css.js:28:16)
    at DestroyableTransform.emit (events.js:194:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:441:20)
    at onwriteError (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/readable-stream/lib/_stream_writable.js:449:12)
    at onwrite (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/readable-stream/lib/_stream_writable.js:470:11)
    at WritableState.onwrite (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/readable-stream/lib/_stream_writable.js:180:5)
    at DestroyableTransform.afterTransform (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/readable-stream/lib/_stream_transform.js:93:3)
    at errorM (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/gulp-sass/index.js:118:12)
    at Object.callback (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/gulp-sass/index.js:127:16)
    at options.error (/Users/anthonyhorn/localhost/ncst/docroot/sites/default/themes/site/node_modules/node-sass/lib/index.js:294:32)
[15:38:48] 'compile' errored after 2.43 s
[15:38:48] 'default' errored after 2.44 s
anthonyhorn@C02Y42X4JGH6 site (master) $ 
`

**Comment by mrkmiller** [comment]
You have to remove `@import "singularitygs";` from your code. We are no longer using it.

**Pull request merged**
